<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="2c678b4f-4941-4cb9-bf4f-3035a8e03eee">
      <driver-ref>ded0b4b2-f05d-4672-8011-3c8e8414bb69</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/locator/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1/django_db</jdbc-url>
      <explain-plan-config>
        <provider>com.intellij.database.plan.mysql.MysqlExplainPlanProvider</provider>
      </explain-plan-config>
    </data-source>
    <data-source source="LOCAL" name="Django default2" uuid="33e55620-534f-4634-9b3a-4f90c7cdc017">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/locator/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:D:\GitHub\anomalyLocator\db.sqlite3</jdbc-url>
    </data-source>
  </component>
</project>